language: java # Work around to make neo4j works.

jdk:
  - oraclejdk8


sudo: true


env:
  - NEO4J_VERSION="3.1.0"


before_install:
  - nvm install 6.9.3
  - nvm use 6.9.3
  # install Neo4j manually:
  - wget dist.neo4j.org/neo4j-community-$NEO4J_VERSION-unix.tar.gz
  - tar -xzf neo4j-community-$NEO4J_VERSION-unix.tar.gz
  - neo4j-community-$NEO4J_VERSION/bin/neo4j start

install:
  - npm install

before_script:
  - curl -vX POST http://neo4j:neo4j@localhost:7474/user/neo4j/password -d"password='$NEO4J_PASS'" 

script:
  - npm test

# this *does* CI pull requests to master and dev:
branches:
  only:
    - master
    - dev